name: Exemplo
on: [push]
jobs:
    Inicial:
      runs-on: ubuntu-latest
      steps:
        - name: Titulo da Taefa
          run: echo "Olá, Mundo! Workflow funcionando! 🎉"
        
        - name: Segunda Tarefa
          run: pwd

        - name: Terceira Tarefa
          run: whoami
